---
title: "poc"
author: "smd"
date: "`r Sys.Date()`"
output: html_document
---



Setup
```{r}
setwd("~/GitHub/csv_scd2")
library(tidyverse)  # data manipulation
library(janitor)    # cleaning up names
library(logger)
library(digest)     # SHA256 hashing
library(fs)         # file manipulation

# makes log text colourful
log_layout(layout_glue_colors)
```

hashing function to facilitate easy comparisons 
```{r}
make_hash <- function(.data, key_cols) {
  ignore_cols <- c("effective_date", "expiry_date", "load_date")
  
  all_cols <- .data %>%  
    colnames() %>% 
    setdiff(ignore_cols)
  
  value_cols <- setdiff(all_cols, key_cols)
  
  if (length(all_cols) == length(value_cols)) {
    log_fatal("The key columns do not exist in the table!")
  } else {
    .data <- .data %>% 
      unite("key_combined", all_of(key_cols), sep = "|", remove = FALSE) %>% 
      mutate(key_hash = sapply(key_combined, digest, algo = "sha256")) %>% 
      unite("value_combined", all_of(value_cols), sep = "|", remove = FALSE) %>%
      mutate(value_hash = sapply(value_combined, digest, algo = "sha256")) %>% 
      select(-c(key_combined, value_combined))
  
    return(.data)
  }  
}

```


```{r}

test_data <- read_csv("test_all.csv", show_col_types = FALSE) %>% 
  clean_names()

```




```{r}
historic_filename <- "historic.csv"

init_historic_table <- test_data %>% 
  filter(between(id, 1, 10)) %>%   
  mutate(effective_date = ymd("1111/01/01")) %>% 
  mutate(expiry_date = ymd("9999/12/31")) %>% 
  mutate(current_record = TRUE)

write_csv(init_historic_table, historic_filename)
  
```

```{r}
load_filename <- "load.csv"

init_load_table <- test_data %>% 
  filter(between(id, 11, 20))

write_csv(init_load_table, load_filename)

```



```{r}
key_cols <- c("name")

# does historic file exist?




# checking for historic file.  If I have it, then check that it is well formed.
have_historic <- file_exists(historic_filename)
if (have_historic) {
  historic_table <- read_csv(historic_filename, show_col_types = FALSE) %>% 
    clean_names()
  
  historic_cols <- colnames(historic_table)
  required_cols <- c(key_list, "effective_date", "expiry_date", "current_record")
  
  if (!all(required_cols %in% historic_cols)) {
    log_fatal(paste0("Historic file (", historic_filename, ") is malformed. Table must have all key columns, effective_date, expiry_date, current_record!"))
  } 
  
  value_cols = setdiff(historic_cols, required_cols)
}

# Checking for load file.  If I have it, then check that it is well formed.
have_load <- file_exists(load_filename)
if (have_load) {
  load_table <- read_csv(load_filename, , show_col_types = FALSE) %>% 
    clean_names() 
  
  if (!all(key_cols %in% col_names(load_table))) {
    log_fatal(paste0("Load file (", load_filename, ") is malformed. Table must have all key columns!"))
  
  } 
} else {
  log_fatal("No load file found!")
}

# If I don't have a historic file, turn the load file into a historic file. 
if (!have_historic & have_load) {
  log_info("No historic table has been found. Converting load table (", load_filename, ") into the historic table.")
  
  load_table %>%   
  mutate(effective_date = ymd("1111/01/01")) %>% 
  mutate(expiry_date = ymd("9999/12/31")) %>% 
  mutate(current_record = TRUE)
    
}


  
  


# if there is no historic table turn the load table into the historic if it is there, if not error out

# do they both have the same key column
# do they both have 

# does historic table exist?
# does it have effective and expiry dates










# need to check for column match before proceeding
# - does historic have the effective and expiry date columns, current flag, hashes???
# - does the load table have the matching columns for the historic


historic_hashes <- historic_table %>% 
  select(key_hash, value_hash, effective_date, expiry_date)  

load_hashes <- load_table %>% 
  select(key_hash, value_hash, load_date) 

# check for hash uniqueness in load key values !!!!!!!!!!

```


```{r}
new_hashes <- anti_join(load_hashes, historic_hashes, by = join_by(key_hash, value_hash))

capped_hashes <- new_hashes %>% 
  select(key_hash, load_date) %>% 
  left_join(historic_hashes, ., by = join_by(key_hash)) %>% 
  mutate(expiry_date = if_else(is.na(load_date), expiry_date, load_date - days())) %>% 
  select(-load_date)

out <- new_hashes %>% 
  rename(effective_date = load_date) %>% 
  mutate(expiry_date = ymd("9999/12/31")) %>% 
  bind_rows(capped_hashes, .) %>%
  left_join(., all_data, by = join_by(key_hash, value_hash)) %>% 
  mutate(current_record = expiry_date == ymd("9999/12/31")) %>% 
  arrange(name, effective_date) 


# add Current Record boolean!!!!

  
```



